# MARK: Configuration
# =============================================================================

name: HealthTracker

options:
  bundleIdPrefix: com.MohdFareed
  deploymentTarget:
    iOS: 18.0
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

# MARK: Dependencies
# =============================================================================

packages:
  HealthTracker:
    path: .

# MARK: Project Files
# =============================================================================
# REVIEW: check synced folder support:
# https://github.com/yonaskolb/XcodeGen/pull/1541

fileGroups:
  - Configuration
  - Assets
  - README.md

# MARK: Settings
# =============================================================================

settings:
  # App Info
  INFOPLIST_KEY_LSApplicationCategoryType:
    - public.app-category.healthcare-fitness
  INFOPLIST_KEY_CFBundleDisplayName: Health Tracker
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 1.0
  DEVELOPMENT_TEAM: B67CHZC3GP

  # Asset Catalog
  ASSETCATALOG_COMPILER_APPICON_NAME: AppLogo
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: Accent
  ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: true
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true

  # Build Settings
  SWIFT_VERSION: 6.0
  DEAD_CODE_STRIPPING: true
  ENABLE_USER_SCRIPT_SANDBOXING: true
  GENERATE_INFOPLIST_FILE: true
  CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true

# MARK: Targets
# =============================================================================

targets:
  HealthTracker:
    type: application
    platform: iOS
    sources:
      - App
      - path: Assets
        buildPhase: resources

    scheme:
      testTargets:
        - HealthTrackerTests
        - HealthTrackerUITests
      gatherCoverageData: true

    entitlements:
      path: Configuration/App.entitlements # signing entitlements
      properties:
        com.apple.developer.healthkit: true

    info:
      path: Configuration/AppInfo.plist
      properties:
        UILaunchScreen:
          UIColorName: AccentColor
          UIImageName: AppLogo
        NSHealthShareUsageDescription: |
          Show your Apple Health data in the app.
        NSHealthUpdateUsageDescription: |
          Backup your app data to Apple Health.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  # MARK: Tests Targets
  # ===========================================================================

  HealthTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests/AppTests
    options:
      - transitivelyLinkDependencies: true
    dependencies:
      - target: HealthTracker

  HealthTrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: Tests/UITests
    options:
      - transitivelyLinkDependencies: true
    dependencies:
      - target: HealthTracker
