# MARK: Configuration
# =============================================================================

name: HealthBank

options:
  bundleIdPrefix: com.MohdFareed
  deploymentTarget:
    iOS: 18.0
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

# MARK: Dependencies
# =============================================================================

packages:
  HealthBank:
    path: .

# MARK: Project Files
# =============================================================================
# REVIEW: check synced folder support:
# https://github.com/yonaskolb/XcodeGen/pull/1541

fileGroups:
  # folders
  - .github
  - .vscode
  - App
  - Assets
  - Scripts
  # files
  - .gitignore
  - Package.swift
  - Project.yml
  - README.md

# MARK: Settings
# =============================================================================

settings:
  # App Info
  INFOPLIST_KEY_LSApplicationCategoryType:
    - public.app-category.healthcare-fitness
  INFOPLIST_KEY_CFBundleDisplayName: Health Bank
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 1.0
  DEVELOPMENT_TEAM: ${HEALTH_BANK_TEAM_ID}

  # Asset Catalog
  ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: Accent
  ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: true
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: false

  # Build Settings
  SWIFT_VERSION: 6.0
  DEAD_CODE_STRIPPING: true
  ENABLE_USER_SCRIPT_SANDBOXING: true
  GENERATE_INFOPLIST_FILE: true
  CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true

# MARK: Targets
# =============================================================================

targets:
  HealthBank:
    type: application
    platform: iOS
    sources:
      - App
      - path: Assets
        buildPhase: resources

    scheme:
      testTargets:
        - HealthBankTests
        - HealthBankUITests
      gatherCoverageData: true

    entitlements:
      path: HealthBank.xcodeproj/App.entitlements # signing entitlements
      properties:
        com.apple.developer.healthkit: true

    info: # App Metadata
      path: HealthBank.xcodeproj/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: LaunchScreenBG
          UIImageName: LaunchScreenLogo
        NSHealthShareUsageDescription: |
          Show your Apple Health data in the app.
        NSHealthUpdateUsageDescription: |
          Backup your local data to Apple Health.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  # MARK: Tests Targets
  # ===========================================================================

  HealthBankTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests/AppTests
    options:
      - transitivelyLinkDependencies: true
    dependencies:
      - target: HealthBank

  HealthBankUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: Tests/UITests
    options:
      - transitivelyLinkDependencies: true
    dependencies:
      - target: HealthBank
