name: HealthTracker
configs:
  Debug: debug
  Release: release

settings:
  DEVELOPMENT_TEAM: B67CHZC3GP
  SWIFT_VERSION: 6.0
  DEAD_CODE_STRIPPING: true
  ENABLE_USER_SCRIPT_SANDBOXING: true
  GENERATE_INFOPLIST_FILE: true
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
  CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true

  INFOPLIST_KEY_LSApplicationCategoryType:
    - public.app-category.healthcare-fitness
  INFOPLIST_KEY_CFBundleDisplayName: Health Tracker
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 1.0

  ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: true

options:
  bundleIdPrefix: com.MohdFareed
  deploymentTarget:
    iOS: 18.0
  createIntermediateGroups: true

include: # Build targets
  - path: Configuration/Targets.yml
    relativePaths: false

packages: # SPM dependencies
  HealthTracker:
    path: .

fileGroups: # Project files
  - Assets
  - Configuration
  - README.md
